let dados = [ 
    {
    titulo : "Quem sou eu:",
    descricao : "• Mulher • Mãe • Avó • Noiva • Amiga • Amo a natureza e o mar  •  Amo caminhadas e trilhas• Amo os detalhes e as gentilezas • Amo uma mesa posta e acompanhada• Amo cafeterias • Amo ler • Amo cinema • Amo conhecer lugares novos.",
    link : "https://www.instagram.com/psijaquelinevieira/",
    Tags : "sobre apresentação tempo livre pessoal"
},
{
    titulo : "Minhas formações:",
    descricao : "<b>• Sou Formada em  Psicologia</b>, <br> <b> • Formada em TCC</b> - que quer dizer: Terapia Cognitivo-Comportamental   e também sou  <br>  <b>• Pós Graduada em Psicologia Positiva</b>, <br>  •• Também possuo  outros cursos com foco em: Depressão, Ansiedade, Obesidade e a mulher no processo de envelhecimento ",
    link : "https://pt.wikipedia.org/wiki/Terapia_cognitivo-comportamental",
    Tags : "faculdade curso estudo escola diploma terapia"

},
{
    titulo : "Minhas Áreas de foco:",
    descricao : "Auxilio o cliente no autoconhecimento, a alcançar suas metas, também na organização do seu dia a dia e autonomia emocional. Esse serviço profissional pode auxiliá-lo em transtornos/sintomas como: depressão, ansiedade, estresse, luto, problemas de relacionamentos, baixa auto-estima, entre outros. ",
    link : " ",
    Tags : "resultado trabalha atende"

},

];